### ISSUE TITLE
harbor_project_member_group not working for 'oidc' type new group

### ISSUE THREAD

**Issue by haiwu** [goharbor/terraform-provider-harbor#177]
**Describe the bug**
harbor_project_member_group not working for 'oidc' type new group

**To Reproduce**
Just try to assign an OIDC group 'sample_oidc_group_name' to a sample project. It would try to ensure this, but nothing happened if checking from harbor GUI. It seems this is not doing anything. 

resource "harbor_project_member_group" "sample_oidc_group_name" {
  project_id = harbor_project.projectname.project_id
  group_name = "sample_oidc_group_name" 
  role = "master"
  type = "oidc"
}

**Expected behavior**
should work

This happens with latest release, and a few versions before that. Has this been tested ok with some OIDC integration?

**Comment by wrighbr** [comment]
@haiwu what version of the provider are you using? There was a breaking change in v3.4.3 which has been fixed. code should look like below

```hcl
resource "harbor_project_member_group" "sample_oidc_group_name" {
project_id = harbor_project.projectname.id
group_name = "sample_oidc_group_name"
role = "master"
type = "oidc"
}
```

**Comment by haiwu** [comment]
Hi, I was some version before 3.4.3. Then I upgrade it to version 3.4.3, still failed the same. I Just upgraded it to version 3.4.4, it is still failing the same. Harbor version I have here is the latest version 2.4.0. It seems it did something, and it remembers that state, but there's nothing showing up in the relevant project "membership" tab, even after I restarted everything for harbor. 

Another issue I found out is that the "harbor_interrogation_services" failed to configure. I tried to set that to 'Daily', it seems it did something and it could remember its state, but nothing got updated from harbor side. 

Other things are still working fine. So this is weird.
